spring:
  application:
    name: gateway
  cloud:
    gateway:
      filter:
        secure-headers:
          disable: "content-security-policy"
          strict-transport-security: max-age=31536000; includeSubDomains
          frame-options: SAMEORIGIN
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
          predicates:
            - name: Path
              args:
                pattern: "'/api/'+serviceId.toLowerCase()+'/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'/api/' + serviceId.toLowerCase() + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"

eureka:
  client:
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:8081/eureka/